version: "3.8"

services:
  # sql:
  #   image: mysql:8.0.32
  #   restart: always
  #   container_name: "sql"
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "password"
  #     MYSQL_DATABASE: "moneyhook"
  #     MYSQL_USER: "moneyhook"
  #     MYSQL_PASSWORD: "password"
  #   volumes:
  #     - ./sql/:/docker-entrypoint-initdb.d/
  #     - ./sql/mysql.cnf:/etc/mysql/conf.d/my.cnf
  #     - ./sql/settings:/var/lib/mysql
  psql:
    image: postgres:17
    restart: always
    container_name: "psql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "moneyhook"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "moneyhook"
    volumes:
      - ./psql/init:/docker-entrypoint-initdb.d/
      - ./psql/data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: "pgadmin"
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./psql/pgadmin_data/servers.json:/pgadmin4/servers.json
    depends_on:
      - psql
  go:
    container_name: app
    volumes:
      - ./:/workspace/
    tty: true
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_TYPE: "PostgreSQL" # "MySQL" or "PostgreSQL"
      # MySQL
      MYSQL_HOST: "sql:3306"
      MYSQL_DATABASE: "moneyhook"
      MYSQL_USER: "moneyhook"
      MYSQL_PASSWORD: "password"
      NET: "tcp" # "unix" or "tcp"
      # PostgreSQL
      POSTGRES_HOST: "psql"
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: "moneyhook"
      POSTGRES_USER: "moneyhook"
      POSTGRES_PASSWORD: "password"
      SSLMODE: "disable" # "disable" or "verify-full"
      # Firebase
      SECRET_PATH: "secret/firebase_secret.json"
      ENABLE_FIREBASE_AUTH: false
