version: "3.8"

services:
  sql:
    image: mysql:8.0.32
    restart: always
    container_name: "sql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "moneyhook"
      MYSQL_USER: "moneyhook"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./sql/mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./sql/settings:/var/lib/mysql
  go:
    container_name: app
    volumes:
      - ./:/workspace/
    tty: true
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: "sql:3306"
      MYSQL_DATABASE: "moneyhook"
      MYSQL_USER: "moneyhook"
      MYSQL_PASSWORD: "password"
      NET: "tcp" # "unix" or "tcp"
      GOOGLE_APPLICATION_CREDENTIALS: "secret/firebase_secret.json"
      ENABLE_FIREBASE_AUTH: false
