FROM golang:1.27.0-alpine

RUN apk add --no-cache git

WORKDIR /workspace

ENV CGO_ENABLED=0

RUN go install github.com/air-verse/air@v1.52.3 \
	&& go install golang.org/x/tools/gopls@v0.23.0 \
	&& go install github.com/cweill/gotests/gotests@v1.6.0 \
	&& go install github.com/fatih/gomodifytags@v1.16.0 \
	&& go install github.com/josharian/impl@v1.1.0 \
	&& go install github.com/haya14busa/goplay/cmd/goplay@v1.0.0 \
	&& go install github.com/go-delve/delve/cmd/dlv@v1.9.0 \
	&& go install honnef.co/go/tools/cmd/staticcheck@v0.4.3 \
	&& go install golang.org/x/tools/cmd/goimports@v0.1.10

EXPOSE 8080

CMD ["sleep", "infinity"]
