package handler

import (
	"MoneyHook/MoneyHook-API/router"

	"github.com/labstack/echo/v4"
)

func (h *Handler) Register(api *echo.Group) {
	authMiddleware := router.FirebaseAuthMiddleware(h.firebaseClient, h.userStore)
	protected := api.Group("", authMiddleware)
	schedulerProtected := api.Group("/job", router.SchedulerAuthMiddleware(h.schedulerToken, h.schedulerAuth))

	reactV1 := protected.Group("/v1")
	reactV1.GET("/households", h.household.List)
	reactV1.POST("/households", h.household.Create)
	reactV1.GET("/households/:householdId", h.household.Get)
	reactV1.PATCH("/households/:householdId", h.household.Rename)
	reactV1.GET("/households/:householdId/members", h.household.Members)
	reactV1.PATCH("/households/:householdId/members/me", h.household.RenameMember)
	reactV1.POST("/households/:householdId/admin-transfer", h.household.Transfer)
	reactV1.POST("/households/:householdId/leave", h.household.Leave)
	reactV1.POST("/households/:householdId/archive", h.household.Archive)
	reactV1.DELETE("/households/:householdId/members/:memberId", h.household.RemoveMember)
	reactV1.GET("/households/:householdId/invitations", h.household.Invitations)
	reactV1.POST("/households/:householdId/invitations", h.household.Issue)
	reactV1.POST("/households/:householdId/invitations/:invitationId/reissue", h.household.Reissue)
	reactV1.DELETE("/households/:householdId/invitations/:invitationId", h.household.Revoke)
	reactV1.POST("/household-invitations/preview", h.household.Preview)
	reactV1.POST("/household-invitations/accept", h.household.Accept)
	reactV1.GET("/households/:householdId/entries", h.household.Entries)
	reactV1.GET("/households/:householdId/entries/:entryId", h.household.Entry)
	reactV1.POST("/households/:householdId/entries/:entryId/corrections", h.household.Correct)
	reactV1.POST("/households/:householdId/own-transactions", h.household.Own)
	reactV1.POST("/households/:householdId/proxy-transactions", h.household.Proxy)
	reactV1.PATCH("/households/:householdId/proxy-transactions/:entryId", h.household.UpdateProxy)
	reactV1.DELETE("/households/:householdId/proxy-transactions/:entryId", h.household.DeleteProxy)
	reactV1.GET("/households/:householdId/shares/:transactionId", h.household.ShareStatus)
	reactV1.PUT("/households/:householdId/shares/:transactionId", h.household.Share)
	reactV1.DELETE("/households/:householdId/shares/:transactionId", h.household.Unshare)
	reactV1.GET("/households/:householdId/payments", h.household.Payments)
	reactV1.POST("/households/:householdId/payments", h.household.SavePayments)
	reactV1.PATCH("/households/:householdId/payments/:referenceId", h.household.SavePayments)
	reactV1.GET("/households/:householdId/categories", h.household.Subcategories)
	reactV1.POST("/households/:householdId/subcategories", h.household.SaveSubcategories)
	reactV1.PATCH("/households/:householdId/subcategories/:referenceId", h.household.SaveSubcategories)
	reactV1.GET("/households/:householdId/analytics/:group", h.household.Analytics)
	reactV1.GET("/households/:householdId/duplicate-candidates", h.household.Duplicates)
	budget := reactV1.Group("/budget")
	budget.GET("", h.budget.GetV1Budget)
	budget.PUT("", h.budget.PutV1Budget)
	settings := reactV1.Group("/settings")
	settings.GET("", h.settings.GetV1Settings)
	settings.PATCH("", h.settings.PatchV1Settings)
	v1Transactions := reactV1.Group("/transactions")
	v1Transactions.GET("/:transactionId", h.transaction.GetV1Transaction)
	v1Transactions.POST("", h.transaction.CreateV1Transaction)
	v1Transactions.GET("", h.transaction.ListV1Transactions)
	v1Transactions.PATCH("/:transactionId", h.transaction.UpdateV1Transaction)
	v1Transactions.DELETE("/:transactionId", h.transaction.DeleteV1Transaction)
	v1Analytics := reactV1.Group("/analytics")
	v1Analytics.GET("/overview", h.analytics.GetV1AnalyticsOverview)
	v1Analytics.GET("/categories", h.analytics.GetV1AnalyticsCategories)
	v1Analytics.GET("/fixed", h.analytics.GetV1AnalyticsFixed)
	v1Analytics.GET("/payments", h.analytics.GetV1AnalyticsPayments)

	transaction := protected.Group("/transaction")
	transaction.GET("/getTimelineData", h.transaction.GetTimelineData)
	transaction.GET("/getMonthlySpendingData", h.transaction.GetMonthlySpendingData)
	transaction.GET("/getTransaction/:transactionId", h.transaction.GetTransaction)
	transaction.GET("/getMonthlyFixedIncome", h.transaction.GetMonthlyFixedIncome)
	transaction.GET("/getMonthlyFixedSpending", h.transaction.GetMonthlyFixedSpending)
	transaction.GET("/getHome", h.transaction.GetHome)
	transaction.GET("/getMonthlyVariableData", h.transaction.GetMonthlyVariableData)
	transaction.GET("/getTotalSpending", h.transaction.GetTotalSpendingData)
	transaction.GET("/groupByPayment", h.transaction.GroupByPayment)
	transaction.GET("/getMonthlyWithdrawalAmount", h.transaction.GetMonthlyWithdrawalAmount)
	transaction.GET("/getFrequentTransactionName", h.transaction.GetFrequentTransactionName)
	transaction.POST("/addTransaction", h.transaction.AddTransaction)
	transaction.POST("/addTransactionList", h.transaction.AddTransactionList)
	transaction.PATCH("/editTransaction", h.transaction.EditTransaction)
	transaction.DELETE("/deleteTransaction/:transactionId", h.transaction.DeleteTransaction)

	fixed := protected.Group("/fixed")
	fixed.GET("/getFixed", h.fixed.GetFixed)
	fixed.GET("/getDeletedFixed", h.fixed.GetDeletedFixed)
	fixed.POST("/addFixed", h.fixed.AddFixed)
	fixed.PATCH("/editFixed", h.fixed.EditFixed)
	fixed.DELETE("/deleteFixed/:monthly_transaction_id", h.fixed.DeleteFixed)

	category := protected.Group("/category")
	category.GET("/getCategoryList", h.category.GetCategoryList)
	category.GET("/getCategoryWithSubCategoryList", h.category.GetCategoryWithSubCategoryList)

	subCategory := protected.Group("/subCategory")
	subCategory.GET("/getSubCategoryList/:categoryId", h.subcategory.GetSubCategoryList)
	subCategory.POST("/editSubCategory", h.subcategory.EditSubCategory)

	payment := protected.Group("/payment")
	payment.GET("/getPayment", h.payment.GetPaymentResourceList)
	payment.POST("/addPayment", h.payment.AddPaymentResource)
	payment.PATCH("/editPayment", h.payment.EditPaymentResource)
	payment.PUT("/reorder", h.payment.ReorderPaymentResources)
	payment.DELETE("/deletePayment/:paymentId", h.payment.DeletePaymentResource)
	payment.GET("/getPaymentType", h.payment.GetPaymentTypeList)

	schedulerProtected.POST("/daily", h.job.ProcessDailyJob)
}
