package migration

const (
	systemUserNo = uint64(1)
	systemUserID = "4f4da417-7693-4fa1-b153-a3511ed1a57a"
)

var masterCategories = []categorySchema{
	{CategoryID: 1, CategoryName: "食費", OrderNum: 1},
	{CategoryID: 2, CategoryName: "外食", OrderNum: 2},
	{CategoryID: 3, CategoryName: "コンビニ", OrderNum: 3},
	{CategoryID: 4, CategoryName: "日用品", OrderNum: 4},
	{CategoryID: 5, CategoryName: "ショッピング", OrderNum: 5},
	{CategoryID: 6, CategoryName: "ファッション", OrderNum: 6},
	{CategoryID: 7, CategoryName: "WEBサービス", OrderNum: 7},
	{CategoryID: 8, CategoryName: "エンタメ", OrderNum: 8},
	{CategoryID: 9, CategoryName: "趣味", OrderNum: 9},
	{CategoryID: 10, CategoryName: "旅行・レジャー", OrderNum: 10},
	{CategoryID: 11, CategoryName: "交際費", OrderNum: 11},
	{CategoryID: 12, CategoryName: "ギフト", OrderNum: 12},
	{CategoryID: 13, CategoryName: "交通費", OrderNum: 13},
	{CategoryID: 14, CategoryName: "美容・コスメ", OrderNum: 14},
	{CategoryID: 15, CategoryName: "医療・健康", OrderNum: 15},
	{CategoryID: 16, CategoryName: "車", OrderNum: 16},
	{CategoryID: 17, CategoryName: "教育", OrderNum: 17},
	{CategoryID: 18, CategoryName: "子供", OrderNum: 18},
	{CategoryID: 19, CategoryName: "手数料", OrderNum: 19},
	{CategoryID: 20, CategoryName: "水道光熱費", OrderNum: 20},
	{CategoryID: 21, CategoryName: "通信費", OrderNum: 21},
	{CategoryID: 22, CategoryName: "住宅", OrderNum: 22},
	{CategoryID: 23, CategoryName: "税金", OrderNum: 23},
	{CategoryID: 24, CategoryName: "保険", OrderNum: 24},
	{CategoryID: 25, CategoryName: "返済", OrderNum: 26},
	{CategoryID: 26, CategoryName: "ビジネス", OrderNum: 27},
	{CategoryID: 27, CategoryName: "給与", OrderNum: 28},
	{CategoryID: 28, CategoryName: "その他収入", OrderNum: 30},
	{CategoryID: 29, CategoryName: "投資", OrderNum: 25},
}

type masterSubCategory struct {
	CategoryID uint64
	Name       string
}

var masterSubCategories = []masterSubCategory{
	{CategoryID: 1, Name: "なし"},
	{CategoryID: 2, Name: "なし"},
	{CategoryID: 2, Name: "カフェ"},
	{CategoryID: 2, Name: "お昼"},
	{CategoryID: 2, Name: "レストラン"},
	{CategoryID: 3, Name: "なし"},
	{CategoryID: 4, Name: "なし"},
	{CategoryID: 5, Name: "なし"},
	{CategoryID: 5, Name: "スポーツ用品"},
	{CategoryID: 5, Name: "ペット"},
	{CategoryID: 5, Name: "電化製品"},
	{CategoryID: 6, Name: "なし"},
	{CategoryID: 7, Name: "なし"},
	{CategoryID: 8, Name: "なし"},
	{CategoryID: 8, Name: "本・雑誌"},
	{CategoryID: 8, Name: "ゲーム"},
	{CategoryID: 8, Name: "音楽"},
	{CategoryID: 8, Name: "映画"},
	{CategoryID: 8, Name: "テレビ"},
	{CategoryID: 9, Name: "なし"},
	{CategoryID: 10, Name: "なし"},
	{CategoryID: 10, Name: "博物館・劇場"},
	{CategoryID: 10, Name: "遊園地"},
	{CategoryID: 10, Name: "ホテル"},
	{CategoryID: 10, Name: "温泉"},
	{CategoryID: 11, Name: "なし"},
	{CategoryID: 11, Name: "ゲームセンター"},
	{CategoryID: 11, Name: "カラオケ"},
	{CategoryID: 11, Name: "居酒屋・バー"},
	{CategoryID: 12, Name: "なし"},
	{CategoryID: 13, Name: "なし"},
	{CategoryID: 14, Name: "なし"},
	{CategoryID: 14, Name: "美容"},
	{CategoryID: 14, Name: "コスメ"},
	{CategoryID: 15, Name: "なし"},
	{CategoryID: 15, Name: "眼科"},
	{CategoryID: 15, Name: "薬"},
	{CategoryID: 15, Name: "病院"},
	{CategoryID: 15, Name: "ジム・フィットネス"},
	{CategoryID: 16, Name: "なし"},
	{CategoryID: 16, Name: "ガソリン"},
	{CategoryID: 16, Name: "駐車場"},
	{CategoryID: 16, Name: "自動車保険"},
	{CategoryID: 16, Name: "有料道路"},
	{CategoryID: 16, Name: "自動車税"},
	{CategoryID: 16, Name: "維持費"},
	{CategoryID: 17, Name: "なし"},
	{CategoryID: 17, Name: "学費"},
	{CategoryID: 17, Name: "学生ローン返済"},
	{CategoryID: 17, Name: "教科書等"},
	{CategoryID: 18, Name: "なし"},
	{CategoryID: 18, Name: "小児科"},
	{CategoryID: 18, Name: "保育園"},
	{CategoryID: 19, Name: "なし"},
	{CategoryID: 19, Name: "利息"},
	{CategoryID: 19, Name: "振込手数料"},
	{CategoryID: 19, Name: "銀行手数料"},
	{CategoryID: 19, Name: "ATM手数料"},
	{CategoryID: 20, Name: "なし"},
	{CategoryID: 20, Name: "電気"},
	{CategoryID: 20, Name: "水道"},
	{CategoryID: 20, Name: "ガス"},
	{CategoryID: 21, Name: "なし"},
	{CategoryID: 21, Name: "携帯電話"},
	{CategoryID: 21, Name: "固定電話"},
	{CategoryID: 21, Name: "インターネット"},
	{CategoryID: 22, Name: "なし"},
	{CategoryID: 22, Name: "家賃"},
	{CategoryID: 22, Name: "住宅設備"},
	{CategoryID: 22, Name: "保険"},
	{CategoryID: 23, Name: "なし"},
	{CategoryID: 23, Name: "住民税"},
	{CategoryID: 24, Name: "なし"},
	{CategoryID: 24, Name: "その他の保険"},
	{CategoryID: 24, Name: "生命保険"},
	{CategoryID: 25, Name: "なし"},
	{CategoryID: 25, Name: "カード引落し"},
	{CategoryID: 26, Name: "なし"},
	{CategoryID: 26, Name: "ビジネス"},
	{CategoryID: 26, Name: "オフィス用品"},
	{CategoryID: 26, Name: "法務会計"},
	{CategoryID: 26, Name: "送料"},
	{CategoryID: 26, Name: "オフィス設備"},
	{CategoryID: 26, Name: "印刷"},
	{CategoryID: 27, Name: "なし"},
	{CategoryID: 27, Name: "ボーナス"},
	{CategoryID: 28, Name: "なし"},
	{CategoryID: 28, Name: "家賃所得"},
	{CategoryID: 28, Name: "利子所得"},
	{CategoryID: 28, Name: "お小遣い"},
	{CategoryID: 29, Name: "なし"},
}

var masterPaymentTypes = []paymentTypeSchema{
	{PaymentTypeID: 1, PaymentTypeName: "現金", IsPaymentDueLater: false, OrderNum: 1},
	{PaymentTypeID: 2, PaymentTypeName: "カード", IsPaymentDueLater: true, OrderNum: 2},
	{PaymentTypeID: 3, PaymentTypeName: "QRペイ", IsPaymentDueLater: false, OrderNum: 3},
}
